trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: katalonTask@1
  displayName: 'Test Katalon with Azure 01'
  inputs:
    version: '8.1.0'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apikey="f3aa28fe-285b-4c61-b85f-a008084fc58a" --config -webui.autoUpdateDrivers=true'